### ISSUE TITLE
error starting django

### ISSUE THREAD

**Issue by viettd14** [nadhirfr/rf-ids#10]
Hi,
I install the following requirement.txt, after I run python3 manage.py runserver I get an error:

will@ubuntu:~/rf-ids/mysite$ python3 manage.py runserver
/home/will/.local/lib/python3.6/site-packages/autobahn/wamp/auth.py:40: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
/home/will/.local/lib/python3.6/site-packages/autobahn/wamp/auth.py:40: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
Performing system checks...

System check identified no issues (0 silenced).
May 05, 2023 - 10:05:08
Django version 2.1.8, using settings 'mysite.settings'
Starting ASGI/Channels version 2.1.7 development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f97a0cd96a8>
Traceback (most recent call last):
  File "/home/will/.local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/will/.local/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 101, in inner_run
    application=self.get_application(options),
  File "/home/will/.local/lib/python3.6/site-packages/channels/management/commands/runserver.py", line 126, in get_application
    return StaticFilesWrapper(get_default_application())
  File "/home/will/.local/lib/python3.6/site-packages/channels/routing.py", line 33, in get_default_application
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/will/rf-ids/mysite/mysite/routing.py", line 4, in <module>
    import app.routing
  File "/home/will/rf-ids/mysite/app/routing.py", line 7, in <module>
    from . import ddos
  File "/home/will/rf-ids/mysite/app/ddos.py", line 25, in <module>
    class GenerateConsumer(AsyncWebsocketConsumer):
  File "/home/will/rf-ids/mysite/app/ddos.py", line 33, in GenerateConsumer
    model = joblib.load(file_path)
  File "/home/will/.local/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 598, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/will/.local/lib/python3.6/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 526, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.6/pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 118

**Comment by medzo-kali** [comment]
Hello
have you found a solution for this issue ?
